services:
  character_engine:
    container_name: character-engine
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 3072M
