version: '3.8'

services:
  personality-engine-discord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personality-engine-discord
    restart: unless-stopped
    volumes:
      - ./src:/app/src  # Mount as a volume
      - ./submodules:/app/submodules  # Mount submodules as volume
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: