services:
  character_engine:
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M
