// <auto-generated />
using System;
using CharacterEngineDiscord.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharacterEngineDiscord.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20230720140404_INIT")]
    partial class INIT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.Channel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Greeting")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImageGenEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Interactions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tgt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.CharacterWebhook", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveHistoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CallPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableTranslator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntegrationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessagesFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("ReplyChance")
                        .HasColumnType("REAL");

                    b.Property<int>("ReplyDelay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslateLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterWebhooks");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.Guild", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultUserToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.History", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("CharacterWebhookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterWebhookId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.HuntedUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Chance")
                        .HasColumnType("REAL");

                    b.Property<ulong?>("CharacterWebhookId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterWebhookId");

                    b.ToTable("HuntedUsers");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.IgnoredUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IgnoredUsers");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.Channel", b =>
                {
                    b.HasOne("CharacterEngineDiscord.Models.Database.Guild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.CharacterWebhook", b =>
                {
                    b.HasOne("CharacterEngineDiscord.Models.Database.Channel", "Channel")
                        .WithMany("CharacterWebhooks")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharacterEngineDiscord.Models.Database.Character", "Character")
                        .WithMany("WebhooksWithThisCharacter")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.Guild", b =>
                {
                    b.HasOne("CharacterEngineDiscord.Models.Database.Character", null)
                        .WithMany("GuildsWhereCharacterIsDefault")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.History", b =>
                {
                    b.HasOne("CharacterEngineDiscord.Models.Database.CharacterWebhook", "CharacterWebhook")
                        .WithMany("Histories")
                        .HasForeignKey("CharacterWebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterWebhook");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.HuntedUser", b =>
                {
                    b.HasOne("CharacterEngineDiscord.Models.Database.CharacterWebhook", null)
                        .WithMany("HuntedUsers")
                        .HasForeignKey("CharacterWebhookId");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.Channel", b =>
                {
                    b.Navigation("CharacterWebhooks");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.Character", b =>
                {
                    b.Navigation("GuildsWhereCharacterIsDefault");

                    b.Navigation("WebhooksWithThisCharacter");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.CharacterWebhook", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("HuntedUsers");
                });

            modelBuilder.Entity("CharacterEngineDiscord.Models.Database.Guild", b =>
                {
                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
