namespace CharacterEngineDiscord.DataAccess.Models.Discord;

/// <summary>
/// A Discord guild (server) the bot is or was a member of.
/// Records are never hard-deleted; presence is tracked via <see cref="Joined"/> + <see cref="LeftAt"/>.
/// </summary>
public sealed class DiscordGuild
{
    /// <summary>Discord snowflake. Generated by Discord; never re-used.</summary>
    public ulong Id { get; init; }

    /// <summary>Guild display name. Mutable — Discord owners can rename guilds.</summary>
    public required string Name { get; set; }

    /// <summary>Snowflake of the current guild owner.</summary>
    public ulong OwnerId { get; set; }

    /// <summary>
    /// Cached owner username. Nullable because the bot might miss the cache or
    /// the user's privacy settings can hide it.
    /// </summary>
    public string? OwnerUsername { get; set; }

    /// <summary>Last known member count (snapshot, not a live counter).</summary>
    public int MemberCount { get; set; }

    /// <summary>Cached guild icon URL. Nullable — guilds without a custom icon, or cache miss.</summary>
    public string? IconUrl { get; set; }

    /// <summary>
    /// True if the bot is currently a member of this guild.
    /// Used as a soft-delete marker via the global query filter on <see cref="AppDbContext"/>.
    /// </summary>
    public bool Joined { get; set; } = true;

    /// <summary>Timestamp of the most recent join. Updated on rejoin.</summary>
    public DateTime JoinedAt { get; set; }

    /// <summary>Timestamp of the most recent leave. Null while the bot is in the guild.</summary>
    public DateTime? LeftAt { get; set; }

    /// <summary>Row-creation timestamp. Defaulted to <c>now()</c> by the database; immutable from app code.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>Last write timestamp. Updated by handlers when mutating fields.</summary>
    public DateTime UpdatedAt { get; set; }
}
